export const SET_DATA_IN_STORE ='SET_DATA_IN_STORE';
export const CHECK_ITEM = 'CHECK_ITEM';
export const UNCHECK_ITEM = 'UNCHECK_ITEM';
export const CLEAR_DATA_SELECT = 'CLEAR_DATA_SELECT';
export const GET_DATA_IN_STORAGE = 'GET_DATA_IN_STORAGE';
export const SYNCHRONIZE = 'SYNCHRONIZE';
export const SAVE_IMAGES = 'SAVE_IMAGES';
export const SET_HOME_LOADER_VISIBLE = 'SET_HOME_LOADER_VISIBLE';